const uclaBuildings = [
    { value: 'Royce Hall', label: 'Royce Hall' },
    { value: 'Powell Library', label: 'Powell Library' },
    { value: 'Kerckhoff Hall', label: 'Kerckhoff Hall' },
    { value: 'Boelter Hall', label: 'Boelter Hall' },
    { value: 'Ackerman Union', label: 'Ackerman Union' },
    { value: 'Math Sciences Building', label: 'Math Sciences Building' },
    { value: 'Franz Hall', label: 'Franz Hall' },
    { value: 'Engineering VI', label: 'Engineering VI' },
    { value: 'Young Research Library', label: 'Young Research Library' },
    { value: 'Schoenberg Music Building', label: 'Schoenberg Music Building' },
    { value: 'Janss Steps', label: 'Janss Steps' },
    { value: 'Haines Hall', label: 'Haines Hall' },
    { value: 'Anderson School of Management', label: 'Anderson School of Management' },
    { value: 'Sproul Hall', label: 'Sproul Hall' },
    { value: 'Dodd Hall', label: 'Dodd Hall' },
    { value: 'Meyer and Renee Luskin Conference Center', label: 'Meyer and Renee Luskin Conference Center' },
    { value: 'The Court of Sciences', label: 'The Court of Sciences' },
    { value: 'Rieber Hall', label: 'Rieber Hall' },
    { value: 'Ostin Music Center', label: 'Ostin Music Center' },
    { value: 'Semel Institute for Neuroscience and Human Behavior', label: 'Semel Institute for Neuroscience and Human Behavior' },
    { value: 'Botany Building', label: 'Botany Building' },
    { value: 'Public Affairs Building', label: 'Public Affairs Building' },
    { value: 'Marshall Field Building', label: 'Marshall Field Building' },
    { value: 'Geology Building', label: 'Geology Building' },
    { value: 'Rolfe Hall', label: 'Rolfe Hall' },
    { value: 'Murphy Hall', label: 'Murphy Hall' },
    { value: 'Bohnett Residential Center', label: 'Bohnett Residential Center' },
    { value: 'Pauley Pavilion', label: 'Pauley Pavilion' },
    { value: 'Ronald Reagan UCLA Medical Center', label: 'Ronald Reagan UCLA Medical Center' },
    { value: 'Semel HCI Institute', label: 'Semel HCI Institute' },
    { value: 'Sunset Canyon Recreation Center', label: 'Sunset Canyon Recreation Center' },
    { value: 'John Wooden Center', label: 'John Wooden Center' },
    { value: 'Kinross Recreation Center', label: 'Kinross Recreation Center' },
    { value: 'Mo Ostin Basketball Center', label: 'Mo Ostin Basketball Center' },
    { value: 'David Geffen School of Medicine', label: 'David Geffen School of Medicine' },
    { value: 'UCLA Meteorite Gallery', label: 'UCLA Meteorite Gallery' },
    { value: 'Fowler Museum', label: 'Fowler Museum' },
    { value: 'Hilltop Structure', label: 'Hilltop Structure' },
    { value: 'Court of Sciences Student Center', label: 'Court of Sciences Student Center' },
    { value: 'UCLA Store', label: 'UCLA Store' },
    { value: 'James West Alumni Center', label: 'James West Alumni Center' },
    { value: 'Franklin D. Murphy Sculpture Garden', label: 'Franklin D. Murphy Sculpture Garden' },
    { value: 'Sculpture Garden at the Hammer Museum', label: 'Sculpture Garden at the Hammer Museum' },
    { value: 'UCLA Lake Arrowhead Conference Center', label: 'UCLA Lake Arrowhead Conference Center' },
    { value: 'William Andrews Clark Memorial Library', label: 'William Andrews Clark Memorial Library' },
    { value: 'Armand Hammer Museum of Art and Culture Center', label: 'Armand Hammer Museum of Art and Culture Center' },
    { value: 'UCLA Mildred E. Mathias Botanical Garden', label: 'UCLA Mildred E. Mathias Botanical Garden' },
    { value: 'Los Angeles Tennis Center', label: 'Los Angeles Tennis Center' },
    { value: 'The Bruin Bear', label: 'The Bruin Bear' },
    { value: 'Kinsey Pavilion', label: 'Kinsey Pavilion' },
    { value: 'Court of Sciences', label: 'Court of Sciences' },
    { value: 'Frisco Building', label: 'Frisco Building' },
    { value: 'Physics and Astronomy Building', label: 'Physics and Astronomy Building' },
    { value: 'Semel HCI Institute', label: 'Semel HCI Institute' },
    { value: 'Terasaki Life Sciences Building', label: 'Terasaki Life Sciences Building' },
    { value: 'Gonda (Goldschmied) Neuroscience and Genetics Research Center', label: 'Gonda (Goldschmied) Neuroscience and Genetics Research Center' },
    { value: 'Dentistry Building', label: 'Dentistry Building' },
    { value: 'Boathouse', label: 'Boathouse' },
    { value: 'UCLA Police Department', label: 'UCLA Police Department' },
    { value: 'UCLA Health Training Center', label: 'UCLA Health Training Center' },
    { value: 'Center for the Art of Performance at UCLA', label: 'Center for the Art of Performance at UCLA' },
    { value: 'Moore Hall', label: 'Moore Hall' },
    { value: 'UCLA Stunt Ranch Reserve', label: 'UCLA Stunt Ranch Reserve' },
    { value: 'UCLA Extension Lindbrook Center', label: 'UCLA Extension Lindbrook Center' },
    { value: 'School of Law - Hugh and Hazel Darling Law Library', label: 'School of Law - Hugh and Hazel Darling Law Library' },
    { value: 'UCLA Store - Lu Valle Commons', label: 'UCLA Store - Lu Valle Commons' },
    { value: 'Inverted Fountain', label: 'Inverted Fountain' },
    { value: 'University Apartments - Weyburn Terrace', label: 'University Apartments - Weyburn Terrace' },
    { value: 'Center for Heterogeneous Integration and Performance Scaling', label: 'Center for Heterogeneous Integration and Performance Scaling' },
    { value: 'Los Angeles Community College District (LACCD) Van de Kamp Innovation Center', label: 'Los Angeles Community College District (LACCD) Van de Kamp Innovation Center' },
    { value: 'Geffen Hall', label: 'Geffen Hall' },
    { value: 'UCLA Fielding School of Public Health', label: 'UCLA Fielding School of Public Health' },
    { value: 'Ralph J. Bunche Hall', label: 'Ralph J. Bunche Hall' },
    { value: 'UCLA Meteorite Gallery', label: 'UCLA Meteorite Gallery' },
    { value: 'Center for Advanced Surgical and Interventional Technology', label: 'Center for Advanced Surgical and Interventional Technology' },
    { value: 'John C. Liebeskind History of Pain Collection', label: 'John C. Liebeskind History of Pain Collection' },
    { value: 'La Kretz Garden Pavilion', label: 'La Kretz Garden Pavilion' },
    { value: 'Court of Sciences Student Center', label: 'Court of Sciences Student Center' },
    { value: 'UCLA Volunteer Center', label: 'UCLA Volunteer Center' },
    { value: 'Tiverton House', label: 'Tiverton House' },
    { value: 'Public Policy Building', label: 'Public Policy Building' },
    { value: 'UCLA Early Care and Education', label: 'UCLA Early Care and Education' },
    { value: 'Wasserman Football Center', label: 'Wasserman Football Center' },
    { value: 'UCLA Arthur Ashe Student Health and Wellness Center', label: 'UCLA Arthur Ashe Student Health and Wellness Center' },
    { value: 'UCLA Bruin Resource Center', label: 'UCLA Bruin Resource Center' },
    { value: 'UCLA Meyer & Renee Luskin Conference Center', label: 'UCLA Meyer & Renee Luskin Conference Center' },
    { value: 'David Geffen Hall', label: 'David Geffen Hall' },
    { value: 'Kinsey Pavilion', label: 'Kinsey Pavilion' },
    { value: 'UCLA Recreation - Wooden Center West', label: 'UCLA Recreation - Wooden Center West' },
    { value: 'UCLA Health - Santa Monica Medical Center', label: 'UCLA Health - Santa Monica Medical Center' },
    { value: 'UCLA Housing - University Apartments South', label: 'UCLA Housing - University Apartments South' },
];

export default uclaBuildings;